### ISSUE TITLE
Sending an event after opening a websocket

### ISSUE THREAD

**Issue by NaamaGertel** [l3nz/ari4java#103]
Is it possible to send an ari4java event (message) that will indicate that the websocket is open successfully after calling: 'ari.events().eventWebsocket(applicationName, true,  new AriCallback); ' ? or if a timeout occurred and the websocket failed to open?
Thanks.

**Comment by grahambrown11** [comment]
Extension of #85 - allow disable and supply events when connected/disconnected...
