### ISSUE TITLE
Ask for maintainership  

### ISSUE THREAD

**Issue by NaamaGertel** [l3nz/ari4java#104]
Hi,
The company I'm working at forked your project, and because I'm the asterisk with java developer that works with your library, I would love for your permission to maintain ari4java.

Thanks!

**Comment by l3nz** [comment]
Can you get me some more details of what you are working on?

**Comment by NaamaGertel** [comment]
I built a library based on ari4java that is an asynchronous API for running voice applications. The library allows to run Asterisk operations, using java CompletableFuture (https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html). Currently, the library uses Asterisk 14 and ARI protocol. 
Git repository of the library: https://github.com/cloudonix/ARIty 
Because I'm the creator of the library, I'm asking to be the maintainer of ari4java. Thanks.

**Comment by l3nz** [comment]
You work at cloudonix? good 👍 
I will get you commit access to this repo, ok?

**Comment by NaamaGertel** [comment]
Excellent! Thank you :)

**Comment by l3nz** [comment]
You have commit access to this repo. As a first thing, I'd suggest removing the "Looking fro a new maintainer" and adding a paragraph saying you are in charge now.

**Comment by NaamaGertel** [comment]
Thank you! I'll remove it :)

**Comment by NaamaGertel** [comment]
Hi @l3nz ,

I released a new version of ari4java after fixing some issues/pull requests and I would love for some help updating it in maven central

**Comment by l3nz** [comment]
Absolutely! where is it?

**Comment by l3nz** [comment]
Also, I need the pom dependencies (if they are changed).

**Comment by l3nz** [comment]
I just did a clean build and uploaded it.

**Comment by NaamaGertel** [comment]
Thanks!
