### ISSUE TITLE
NettyHttp NIO EVENT loop could not be stopped during Stopping tomcat server

### ISSUE THREAD

**Issue by wdelosan** [l3nz/ari4java#112]
Hello Team :),

 we have a web application running in TOMCAT 8.5 server that send HTTP rest request to an Asterisk using this library and listens to it for responses via websocket using this library as well. 

All is good and working smoothly however when we stop Tomcat it doesn't stop gracefully and in logs we get this trace(Please see below).

Do you have any suggestion how to stop this error so that we can shutdown TOMCAT server without  the errors?

WARNING: The web application [ROOT] appears to have started a thread named [nioEventLoopGroup-2-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
 sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
 sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
 sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
 io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
 io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
 java.lang.Thread.run(Thread.java:748)
Jan 22, 2019 4:03:55 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
WARNING: The web application [ROOT] appears to have started a thread named [nioEventLoopGroup-2-2] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

**Comment by bigno** [comment]
Hi guys!
I work with @wdelosan on the we application that describe in the previous message.

I want add some details about the tool that we use in the WebApplication:
-  Java 8
-  Spring Boot Starter Parent v1.5.18.RELEASE
-  ari4java v0.4.5 (retrieved directly with Maven)

**Comment by titaniche** [comment]
Hi everyone!
I have a similar problem. Are there any solutions?
```
WARNING [http-nio-8080-exec-25] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [WEB-APPLICATION] appears to have started a thread named [nioEventL
oopGroup-2-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
 sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
 sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
 io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:791)
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:439)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
 io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:748)

SEVERE [http-nio-8080-exec-25] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [WEB-APPLICAION] created a ThreadLocal with key of type [java.
lang.ThreadLocal] (value [java.lang.ThreadLocal@36e0bff8]) and a value of type [io.netty.util.internal.InternalThreadLocalMap] (value [io.netty.util.internal.InternalThreadLocalMap@1eb2ded6]) but failed to remove it when t
he web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

**Comment by bigno** [comment]
Hi @titaniche !!
We didn't find a solution to the problem, however the error reported occurred to us in an execution of the Web application inside Tomcat executed by the IDE IntelliJ Idea (on Windows computer). The problem did not occur when I deployed the web application in an instance of Tomcat installed on a CentOs machine.

Unfortunately, I can't provide support.

**Comment by grahambrown11** [comment]
I use Spring Boot too, and I use the `javax.annotation.PostConstruct` and `javax.annotation.PreDestroy` annotations on the bean that starts ARI.
In the `init()` method annotated with `@PostConstruct` I create and instance of `ARI` assigned to a member variable then in the `destory()` method annotated with `@PreDestroy` I call `ari.cleanup()`
