### ISSUE TITLE
Events returning Object are handled as a String

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#12]
TBD

**Comment by manticorps** [comment]
Is there any milestone for this feature ?  Thanks

**Comment by l3nz** [comment]
I am rewriting the code generator. Can you post an example here of what you would expect?

**Comment by manticorps** [comment]
I don't know very well the full ARI, for my case I only use the ChannelUserEvent, but I think there are another place where a String is used instead of JSON.

For me is sufficient to have a JSONObject who contain the event.
```java
public interface ChannelUserevent {
    ...
    public void setUserevent(final JSONObject userEvent );
    public JSONObject getUserevent();
}
```

I think it's the more straightforward to archive this.
