### ISSUE TITLE
ARI eventWebsocket after 1.8.0 requires subscribeAll parameter

### ISSUE THREAD

**Issue by cory107** [l3nz/ari4java#122]
The codegen api's 1.9.0+ requires the boolean parameter "subscribeAll" otherwise the api will break when upgrading. Ideally the codegen should use a default param "false" as indicated in the api documentation for ARI.

A workaround for this issue is to use a switch statement such as:

  actionEvents = ari.events();
   somecallback= new CustomCallback();
   switch (ari.getVersion()) {
         case ARI_0_0_1:
         case ARI_1_5_0:
         case ARI_1_6_0:
         case ARI_1_7_0:
         case ARI_1_8_0:
             actionEvents.eventWebsocket("AppName", somecallback);
             break;
         default:
             actionEvents.eventWebsocket("AppName", false, somecallback);
     }

**Comment by grahambrown11** [comment]
I'm not sure I follow your issue, the subscribeAll parameter was not and still is not required parameter by ARI, the library supports using the param or not.

**Comment by grahambrown11** [comment]
Duplicate of #100
Code generator is creating method but throws an invalid `UnsupportedOperationException("Method availble from ...");`
