### ISSUE TITLE
Compilations Errors.

### ISSUE THREAD

**Issue by wagfeliz** [l3nz/ari4java#142]
// Java Version :
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

// Several errors like this when you try to generate the libs :
C:\Projects2019\java\Asterisk\ari4java\src\main\generated\ch\loway\oss\ari4java\generated\ari_1_0_0\actions\requests\PlaybacksGetRequest_impl_ari_1_0_0.java:41: error: incompatible types: Charset cannot be converted to String
    AriRequest ariRequest = new AriRequest("/playbacks/" + URLEncoder.encode(playbackId, ARI.ENCODING) + "", "GET");

**Comment by grahambrown11** [comment]
Sorry, I use Java 11, it didn't even cross my mind to check that. 
Unfortunately changing it to a string is more involved as it throws a `UnsupportedEncodingException` which needs to be handled.
You could use Java 11 otherwise
