### ISSUE TITLE
Getting HTTP 404 on endpoints request even though if a plain HTTP request returns the correct response

### ISSUE THREAD

**Issue by jbreitung** [l3nz/ari4java#150]
Hi there,

I am trying to get the SIP endpoint of a specific resource via ARI connection. I am opening the connection via ARI.build();

`ARI ari = ARI.build("http://" + server.getIP() + ":8088", "", ariUser, ariPass, AriVersion.ARI_6_0_0);`

After the connection is established I am using the following methods to get the endpoint of my resource:

`Endpoint sipEndpoint = ari.endpoints().get().setTech("SIP").setResource(String.valueOf(userid)).execute();`

The URL to the HTTP server of the Asterisk should be "GET http://10.0.0.70:8088/ari/endpoints/SIP/1001" for this request. 

If I am requesting this URL via CLI or Web-Browser/REST-Client I am getting the correct response of my Asterisk server. If I am requesting the data via ARI, it will throw an RestException with the message "(HTTP 404 Error) Endpoints not found".

**Comment by jbreitung** [comment]
Btw. I am using Asterisk 16.7.0

**Comment by grahambrown11** [comment]
Hi @jbreitung thanks for bringing this up, I'll correct the code so if the supplied URL does not end in a slash then add a slash... but till the next release should do the trick:
`ARI.build("http://" + server.getIP() + ":8088/", "", ariUser, ariPass, AriVersion.ARI_4_0_2);` 
Also a note I changed `ARI_6_0_0` to `ARI_4_0_2` as you said you're using Asterisk 16.7.0 which has ARI 4.0.2, not 6.0.0 so you may experience other issues...
Unfortunately ARI and the corresponding Asterisk versions are not documented, but watch the Wiki  I'll post a page soon that'll hopefully clear that up...
