### ISSUE TITLE
Channel not in stasis-application

### ISSUE THREAD

**Issue by jbreitung** [l3nz/ari4java#152]
Hi there,

am am furthermore trying to integrate Ari4Java into our PBX solution and now I'm at the point where I want to add some channels to a new bridge which I created via ARI before.

When I execute the following code I am getting an exception which says: (HTTP 422 Error) Channel not in Stasis application

```
Bridge bridge = ari.bridges().create().setName("private-conference-" + conference.getRoomNumber()).execute();

ari.bridges().addChannel(bridge.getId(), channelId).execute();
ari.bridges().addChannel(bridge.getId(), linkedId).execute();
```

I don't know what to do that this will work. I tried to add all my channels to an stasis application via dialplan but I was not able to get this working either because Asterisk said my stasis application is not registered.

I am completely new to ARI and stasis, we've never done something with it before, so maybe you have some information for me which helps me to solve this issue.

**Comment by grahambrown11** [comment]
How are you getting `channelId` and `linkedId `?
If they were not from the Websocket `StasisStart` event or not created by ARI4Java then you will get the error. I know in my application I subscribe to the channel in the StasisStart as I want to know when the channel disconnect (use `ari.subscribe(message.getChannel());`...
Before the dialplan can call `Stasis("appname")` you need to have an active Websocket using the `ari.events()` call. I documented a good example [here](https://github.com/l3nz/ari4java/wiki/Examples#weasels)

**Comment by grahambrown11** [comment]
I've also updated the Getting Started with an [Understanding ARI](https://github.com/l3nz/ari4java/wiki/Getting-Started#understanding-ari) section hope that helps
