### ISSUE TITLE
WS reconnect

### ISSUE THREAD

**Issue by modrljin** [l3nz/ari4java#155]
Hi @grahambrown11

I really appreciate your work in this project! I have a fork of this project, but now I see you have bring it to higher level since last time I've done any changes in my fork (long time ago). I've just tried your last release and happy that it works fine. You've added few features that I had a long time ago, such as ws connection events (conneted, disconnected)...
I'd like to add/improve a bit ws stuff and my question is what's is the best way to do that, actually what are my options:
1. I can update my fork to match to your's master, then I do the work and you can merge it if you want?
2. I suppose I can't change a code directly in your project, expecially not in master branch. Is there a possibility to create a new branch in your project?
3. I give you the hint what I would like to add, and you do all the work :)

Here is the list what I'd like to do:

**1. set max count/infinite WS reconnect count to class NettyHttpClient, e.g.**
```
public void setMaxReconnectCount(int count) {
   this.maxReconnectCount = count; // -1 = infinite reconnect attempts
}
```
Infinite reconnect attempts have sense to me when asterisk is down for a while, application doesn't have to take care for handling reconnect after a while

**2. method to check if ws is connected**
```
public boolean isWsConnected() {
    	return wsClientConnection != null && wsChannelFuture != null && 
 wsChannelFuture.channel().isActive();
}
```

**3. debug/improve ws reconnect - currently it works a bit strange. If you stop asterisk while ws is connected, reconnecting works different then defined (after a 2,5,10 seconds), please check the log file...**

![image](https://user-images.githubusercontent.com/22682901/78349479-f47a5b80-75a3-11ea-9479-4fd9140fce52.png)

**4. onFailure(cause) "Cannot connect: WS Connect Timeout - executing failure callback" is called a long time after the cause "WS Connect Error:"**

**5. it would be useful to add new event AriConnectionEvent.WS_RECONNECT_STOPPED on last reconnect attempt failure if max reconnect count is not infinite**

Thank you!
Marin

**Comment by grahambrown11** [comment]
Hey @modrljin thanks for the feedback.
Generally the way open source projects work is you fork the repo make your improvements the send a pull request to get them merged into the original project. It is then up to the project maintainers (which L3nz has graciously granted me) to accept and merge.
So you're welcome to submit the improvements from points 1 & 2 for the infinite auto reconnect you've already applied on your fork but I'd suggest point 5 goes with this improvement if you'd like to include that. As for point 3 & 4 they are related - there was an issue where someone had created a bogus webserver which didn't respond then ARI would hang so I created an internal timer which I suspect it the problem - I'm going to create separate issue for that. 
I look forward to your pull request

**Comment by modrljin** [comment]
Hi @grahambrown11 

Great! I'll finish it probably somewhen at the beginning of the next week and create a pull request. 
About the oher issue #156 will you check that or do you want me also to try to fix it? What I have seen not only there is a problem with calling **onFailure**, but reconnect intervals are somehow irregular. Instead of 2,5,10... seconds, they are executed very strange, sometimes 2 or 3 in the same time. All 10 reconnects finish in cca. 30 seconds.

Thanks!

**Comment by grahambrown11** [comment]
> Hi @grahambrown11
> 
> Great! I'll finish it probably somewhen at the beginning of the next week and create a pull request.
> About the oher issue #156 will you check that or do you want me also to try to fix it? What I have seen not only there is a problem with calling **onFailure**, but reconnect intervals are somehow irregular. Instead of 2,5,10... seconds, they are executed very strange, sometimes 2 or 3 in the same time. All 10 reconnects finish in cca. 30 seconds.
> 
> Thanks!

I'm looking into it now - I think the irregular reconnects are related to the connection check thread

**Comment by modrljin** [comment]
Hi, I've made pull request. Since you have fixed **onFailure**, adding AriConnectionEvent.WS_RECONNECT_STOPPED becomes unnecessary. Thanks!

**Comment by grahambrown11** [comment]
Pull Request merged
