### ISSUE TITLE
How to set variables to channels with setChannelvars?

### ISSUE THREAD

**Issue by adora-tech** [l3nz/ari4java#164]
Hello,

**Documentation:**

https://javadoc.io/doc/ch.loway.oss.ari4java/ari4java/latest/ch/loway/oss/ari4java/generated/models/Channel.html

**In the documentation I found the following:**

setChannelvars
	void setChannelvars​(java.lang.Object val)
	Parameters: val - Channel variables
	Since: ARI_2_0_0

**In code:**

Channel channel = ari.channels().create("PJSIP/6002", ARI_APP).execute();
channel.setChannelvars("CONNECTEDLINE(name)=Caller identity");
System.out.println("CHANNEL VARIABLE: " + channel.getChannelvars());
ari.channels().dial(channel.getId()).setTimeout(30).execute();

At run, we see in the console:

   CHANNEL VARIABLE: CONNECTEDLINE(name)=Caller identity

after we set **setChannelvars**

**In JSON dump:**

{
    "type": "ChannelCreated",
    "timestamp": "2020-11-04T18:27:25.599+0200",
    "channel": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Down",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "ChannelDialplan",
    "timestamp": "2020-11-04T18:27:25.601+0200",
    "dialplan_app": "Stasis",
    "dialplan_app_data": "vm-app",
    "channel": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Down",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "variable": "STASISSTATUS",
    "value": "",
    "type": "ChannelVarset",
    "timestamp": "2020-11-04T18:27:25.601+0200",
    "channel": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Down",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "Dial",
    "timestamp": "2020-11-04T18:27:25.803+0200",
    "dialstatus": "",
    "forward": "",
    "dialstring": "6002",
    "peer": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Down",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "ChannelStateChange",
    "timestamp": "2020-11-04T18:27:25.908+0200",
    "channel": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Ringing",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "Dial",
    "timestamp": "2020-11-04T18:27:25.910+0200",
    "dialstatus": "RINGING",
    "forward": "",
    "dialstring": "",
    "peer": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Ringing",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "Dial",
    "timestamp": "2020-11-04T18:27:25.910+0200",
    "dialstatus": "RINGING",
    "forward": "",
    "dialstring": "",
    "peer": {
        "id": "1604507245.48",
        "name": "PJSIP/6002-0000002d",
        "state": "Ringing",
        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        },
        "accountcode": "",
        "dialplan": {
            "context": "test",
            "exten": "s",
            "priority": 1
        },
        "creationtime": "2020-11-04T18:27:25.599+0200",
        "language": "en"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0",
    "application": "ws-dump"
}

{
    "type": "DeviceStateChanged",
    "application": "ws-dump",
    "timestamp": "2020-11-04T18:27:25.918+0200",
    "device_state": {
        "name": "PJSIP/6002",
        "state": "RINGING"
    },
    "asterisk_id": "00:0c:29:8d:2f:d0"
}
[...]

**In JSON messages I do not see any information populated:**

        "caller": {
            "name": "",
            "number": ""
        },
        "connected": {
            "name": "",
            "number": ""
        }

and the phone shows "Anonymous" on the display.

**What is the proper way to create/format the parameter "java.lang.Object val" for setChannelvars​() method?**

Thank you!
Iulius

**Comment by grahambrown11** [comment]
The object returned from the `execute` is readonly so you have to set the values on the request before executing...
In order to set the CLI you can to add it to the `dial` API as per the [Asterisk docs](https://wiki.asterisk.org/wiki/display/AST/Asterisk+16+Channels+REST+API#Asterisk16ChannelsRESTAPI-dial)
`ari.channels().dial(channel.getId()).setCaller("Caller identity").setTimeout(30).execute();`
Unless you need earlymedia the `originate` API is an easier option
`ari.channels().originate("PJSIP/6002").setApp(APP_NAME).setCallerId("Caller identity").execute()`
