### ISSUE TITLE
Connections as IM_FEELING_LUCKY should autodetect version

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#18]
When you connect as IM_FEELING_LUCKY, you should have a way to know which version is actually in use.
If you connect to an Asterisk that uses a newer version of the ARI, it should use the latest interface; while if you connect using a specific token, it should abort on the wrong version.

**Comment by l3nz** [comment]
Or maybe you should be able to specify a minimum or maximum version, and get an error if out of allowed range.

**Comment by l3nz** [comment]
It should be working now. There was some error in the regexp.

**Comment by Etep15** [comment]
I'm having this issue as well. However I realize that it's likely due to the version I'm running of asterisk (13.7.2). IM_FEELING_LUCKY (version 13.7.0) doesn't work. Nor does trying to use ARI_1_9_0 as it looks like its for 13.5.0.

Any suggestions?
