### ISSUE TITLE
Test of AriFactory connections

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#19]
When we connect through the AriFactory, we should make sure that the connection actually works. Not sure which call to make, I wonder which is the most lightweight one.

**Comment by andrest964** [comment]
I agree with this - I'm trying to get ari4java to connect to asterisk 15.7.0 and I get absolutely no feed back - the connect does not show up in Asterisk and nothing back from HelloAriWorld other than the standard "Hello ARI World!", "There are 0 active channels now." and "System up since : Tue Jan 19 15:03:33 SAST 2016"

**Comment by l3nz** [comment]
Do you have a trace of what goes on between A4j and Asterisk?

**Comment by l3nz** [comment]
You may want to test a different asterisk version - for example you could use one of the docker images here: https://github.com/l3nz/whaleware/tree/master/examples/asterisk-load-test

I plant to make a tutorial using one of those boxes for tests.

**Comment by andrest964** [comment]
Hi l3nz - Thank you for responding :); I rolled back to Asterisk version 13.5 on Friday with the same result I will try and get a sniff this am.

**Comment by andrest964** [comment]
786 --> http://localhost/ari/asterisk/info?api_key=aritest:testme => "I find this odd should it not be the destination server address which is 192.168.25.35" 
[ari-sniff.pcap.zip](https://github.com/l3nz/ari4java/files/102812/ari-sniff.pcap.zip)

**Comment by andrest964** [comment]
BTW: when I run ARI4Java on the asterisk dev box  
http://localhost/ari/asterisk/info?api_key=aritest:testme still does not hold a connection and the url 
is also very different than the command line connection test that does work:
wscat --connect 'ws://localhost:8088/ari/events?app=HelloAriWorld&api_key=aritest:testme'

**Comment by l3nz** [comment]
You may want to have a lok at this: https://github.com/l3nz/ari4java/blob/master/GETTING_STARTED.md
