### ISSUE TITLE
Example of websocket usage

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#21]
Let's bulid an example like https://github.com/svoboda-jan/asterisk-ari/blob/master/examples/websocket.rb for the docs.

**Comment by grahambrown11** [comment]
Will this do?
https://github.com/l3nz/ari4java/blob/master/src/test/java/ch/loway/oss/ari4java/sandbox/sample/Weasels.java

**Comment by grahambrown11** [comment]
Documented in the [Getting Started Wiki](https://github.com/l3nz/ari4java/wiki/Getting-Started)
