### ISSUE TITLE
Adding Event.Type enum for cleaner coding

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#23]
At the moment, when you receive an event, you have to manually check its type and cast it.

Unfortunately Java does not support a syntax like:

  switch ( myEvent.getClass ) {
        case XXX:
           do something....
   }

so you have to resort to long lines of "if (x instanceof EVENT) else ..." that frankly suck.

I would like to have an Event.Type enum and a getType() method in the Event interface so that you can switch over them.

**Comment by manticorps** [comment]
For my advice you can close this "issue", there are at least two pattern to solve this on the user side :
- Use a eventBus (from guava lib) (my favorite)
- Use a visitor pattern 

There is a example with the use a eventBus :

```java
public class CallbackMessage implements AriCallback<Message> {

    // Log4j Logger
    private static final Logger LOG = LoggerFactory.getLogger(CallbackMessage.class);
    private final EventBus bus;

    public CallbackMessage(final EventBus bus) {
        bus.register(this);
        this.bus = bus;
    }

    @Override
    public void onSuccess(final Message result) {
        System.out.println(String.format("Dummy message callback receive [%s] with class [%s]",
                result.getType(),
                result.getClass()));

        bus.post(result);
    }

    @Override
    public void onFailure(RestException e) {
      // Oh noooooo
   }


  @Subscribe
    public void onChannelVarset(final ChannelVarset_impl_ari_1_7_0 channelVarset) {
        System.out.println("here I do what I want with my channel varset");
    }


    @Subscribe
    public void onHangup(final ChannelHangupRequest_impl_ari_1_7_0 channelHangupRequest) {
        System.out.println("here I do what I want with my hangup");
    }

```

**Comment by restfull-user** [comment]
result.getType() always return null...
Can you fix it?

**Comment by l3nz** [comment]
This will be probably fixed with the new code generator.
For the moment, use `instanceof`.
