### ISSUE TITLE
Larger maximum response

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#30]
Since the underlying netty request is limited to 256 (code line 60) \* 1024 KB (code line 87), the request of the list is too big.
To resolve the problem, you can double the size of
public static final int MAX_HTTP_REQUEST_KB = 256;
to
public static final int MAX_HTTP_REQUEST_KB = 512;
on line 60 in NettyHTTPClient.java and recompile.

**Comment by michaelpetruzzellocivicom** [comment]
Is there any downside to having the MAX_HTTP_REQUEST_KB defaulted to 512?

**Comment by l3nz** [comment]
No - but on every call it will allocate 512K of buffer, so when I did it is sounded unlikely that an ARI request was to be so large. If it happens, we can make it bigger.

**Comment by grahambrown11** [comment]
The size was changed in March 2018 to 16MB, going to close this for now...
