### ISSUE TITLE
When prefix is used/uncommented in Asterisk's http.conf HTTP URIs of Actions are formed incorrectly

### ISSUE THREAD

**Issue by bweschke** [l3nz/ari4java#41]
to fix, change line 126 of classes/ch/loway/oss/ari4java/tools/http/NettyHttpClient.java

from:

        HttpVersion.HTTP_1_1, HttpMethod.valueOf(method), "/ari" + path + queryString);

to:

        HttpVersion.HTTP_1_1, HttpMethod.valueOf(method), baseUri.getPath() + "ari" + path + queryString);

**Comment by l3nz** [comment]
Looks good - can you send me a patch?

**Comment by l3nz** [comment]
Patched.

**Comment by bweschke** [comment]
Testing with 0.4.1 - looks like this is now a regression fail.

**Comment by l3nz** [comment]
Fixed.
