### ISSUE TITLE
Received wrong object calling originate action

### ISSUE THREAD

**Issue by pablop992** [l3nz/ari4java#44]
We are trying to use this library to execute a test for 100 calls. When we execute the "Originate" action and wait for the response:

public Channel originate(..) throws RestException {
buildOriginate(...);
String json = httpActionSync();
return deserializeJson( json, Channel_impl_ari_1_9_0.class ); 
}

In the "json" string variable arrives a Playback object of another channel instead of a Channel object of the initialized channel through originate(), so in the deserializeJson method is generated a exception while trying to unmarshal the Json based on the Channel class structure:

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "media_uri" (Class ch.loway.oss.ari4java.generated.ari_1_9_0.models.Channel_impl_ari_1_9_0)﻿

**Comment by l3nz** [comment]
Hello there,
this really sounds weird! can you reproduce the problem with a minimal test?
l.

**Comment by pablop992** [comment]
Hi Lenz,

Thanks for your reply. No, I can't. When I initially test my app based on your library, I executed 10 calls as maximum and anything works OK. Another member of my team try to test the app based on a stress scenario, and when the number of calls reach 100 calls that error is shown.

I suspect that the error could be due to the Netty Http Client, the pipeline handling is so confuse to me, and it could mess the streams. I'm creating a fork based on the apache http client to verify this. I'm telling my conclusion in the next days.

**Comment by l3nz** [comment]
Yes the Netty pipeline is a PITA. But it really sounds strange that things get mixed up....

**Comment by pablop992** [comment]
Hi Lenz,

I do the fork w/ Apache HTTP client, and works perfectly until 100 calls (I haven't tested with more calls, will do in the next hours). But, another problem that I detected is that the Actions that inherit from BaseAriAction will have serious syncronization problems, because the reset() method is called each time i need to execute a command over the ARI, and generates a nullpointerexception when another thread use it. I tried with the following two options:

- Synchronize the Action that I'm using (duh), but it will be a bottleneck if you have many threads/calls.

- Create an Action object each time I want to execute a command over the ARI, this should work nice but strangely it lets execute only 2 or 3 calls of 100. I don't have any idea why happens this.

I like to know your opinion about this scenario, and if you want some hand in development tasks I'm pleased to help you. 

P.S. Your library is awesome!

**Comment by l3nz** [comment]
I am not sure I understand. Every time you want to run an action you run a *different* action, so there should be no synchronization issues. It is *not* meant to be reused.

**Comment by pablop992** [comment]
Hi Lenz, I tried to create a different "Action" object for each action to execute, but the result was unsuccessfull, only 3 calls of 100 was executed correctly. I assume that due to this you have in each Action a reset() method to use only one instance for action type (a kind of Singleton). I do several changes in the library, e.g. changing the websocket and http client, letting the Action as "static" classes, and another fixes, and the result was partly successfull in a stress test of 1000 calls / 50 concurrents. The error is mostly in the Asterisk, when the following error is showed several times: task processor queue reached 500 scheduled tasks, some Playbacks failed to play and so on.

**Comment by grahambrown11** [comment]
@pablop992 I think your issue is you are re-using the object from ARI in multiple threads - that'll be a problem, you need a new object for each thread. The default EventLoop uses 2 times the CPUs reported by java (`Runtime.getRuntime().availableProcessors()`) override this by suppling the system property `io.netty.eventLoopThreads`. I set mine to 10 using `-Dio.netty.eventLoopThreads=10` in the `java` command you can also use `System.setProperty("io.netty.eventLoopThreads", "10");` in your code.
bad:
```
ARI ari = ARIFactory.nettyHttp(...);
ExecutorService executor = Executors.newFixedThreadPool(10);
ActionChannels channels = ari.channels();
for (int i=0; i < 100; i++) {
    executor.execute(() -> {
        channels.originate(...);
    });
}
```
good:
```
ARI ari = ARIFactory.nettyHttp(...);
ExecutorService executor = Executors.newFixedThreadPool(10);
for (int i=0; i < 100; i++) {
    executor.execute(() -> {
        ActionChannels channels = ari.channels();
        channels.originate(...);
    });
}
```

A suggestion on processing the ActionEvents is to create your own thread pool and schedule your application work in your own pool. I found that Asterisk doesn't send the next event until the previous one is complete. My `onSuccess` looks similar to this:
```
ExecutorService executor = Executors.newFixedThreadPool(10);
AriCallback<Message> callback = new AriCallback<Message>() {
            @Override
            public void onSuccess(Message message) {
                logger.debug("ARI onSuccess");
                executor.execute(() -> {
                    if (message instanceof StasisStart) {
                        handleStatisStart((StasisStart) message);
                    }
                });
            }
            @Override
            public void onFailure(RestException e) {
                logger.debug("ARI onFailure", e);
            }
};
```
