### ISSUE TITLE
Automagical WS reconnections

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#46]
Based on the comments in #43 - it would be cool to have an option to have ARI trying reconnections automatically, up to a limit (eg 10 seconds), as not to have to explicitly code for the odd glitch.  
See @grahambrown11

**Comment by grahambrown11** [comment]
Good news, was gracefully given work hours to implement the check as per #52

**Comment by grahambrown11** [comment]
@l3nz I removed and swallowed some of the exceptions for ARI cleanup - there was an issue where the cleanup wouldn't complete as exceptions weren't caught...
I also added another thread group using the Netty NioEventLoopGroup class (simpler than implementing custom ThreadPoolExecutor, this is to try avoid deadlocks occurring when the exception is bubbled back to the main app and that calls cleanup.

**Comment by grahambrown11** [comment]
check #53 closed #52 as I enhanced the cleanup and addressed #51

**Comment by l3nz** [comment]
Good - merged in 0.4.1
