### ISSUE TITLE
Multiple ARI Objects

### ISSUE THREAD

**Issue by michaelpetruzzellocivicom** [l3nz/ari4java#48]
I am using ARI in an environment where there are multiple Asterisk servers that one stasis application is managing. This means I have multiple ARI objects. Also, as it turns out, Asterisk does not scale up very well. In Asterisk only a single thread manages one websocket connection, so for higher call volume multiple websockets are needed to even connect to one server.

When reconnecting a failed connection in this environment, the specific URL for the failed ARI needs to be known. To solve this I have added a url property to the ARI class.

**Comment by l3nz** [comment]
Looks good to me. Closed.
