### ISSUE TITLE
ari4java does not URL encode or escape out double quotes in originate request

### ISSUE THREAD

**Issue by scfcplummy** [l3nz/ari4java#51]
Hi,

I've found that when trying to send e164 as destination and cli in an originate request, these are not url encoded when sent in the ari request - so the '+' is treated as space by Asterisk.

Also, when sending a value in the body on the variables list, if the value has double quotes in it they are not escaped in the actual ari request.

Many thanks

**Comment by grahambrown11** [comment]
I've implemented the encoding in PR #53

**Comment by l3nz** [comment]
Merged in 0.4.1
