### ISSUE TITLE
Commit 0d6d819 reverted fix for proper observation of ARI Endpoint prefix. 

### ISSUE THREAD

**Issue by bweschke** [l3nz/ari4java#57]
The commit in 0d6d819 reverted the fix implemented originally in #42 so now regression for #41 fails.

**Comment by l3nz** [comment]
Should be fixed.

**Comment by bweschke** [comment]
Can you build a new version/package so I can update my pom.xml's from this side rather than having to build manually in my CI environments based on a certain commit hash?

**Comment by l3nz** [comment]
Done!
