### ISSUE TITLE
"Inactive Stasis app 'AriStart' missed message" logs after ari.cleanup()

### ISSUE THREAD

**Issue by modrljin** [l3nz/ari4java#59]
I'm getting log message "Inactive Stasis app 'AriStart' missed message" in Asterisk CLI after I close my ari app with ari.cleanup() method. 

My 'AriStart' app subscribes to all events at the beginning. At the end, after cleanup is called everything seems to be fine, but later, every few minutes I'm getting 'inactive app' message. Here is CLI log:

 Deactivating Stasis app 'AriStart'
  == WebSocket connection from '192.168.0.67:56988' closed
    -- Inactive Stasis app 'AriStart' missed message
    -- Inactive Stasis app 'AriStart' missed message
    -- Inactive Stasis app 'AriStart' missed message
...

I know what is missed message about - one SIP client is always producing PeerStatusChange event for some reason, but this is irrelevant here.

Do I miss something, should I call additionaly unsubscribe all somehow?

**Comment by modrljin** [comment]
I think this is not an issue of ari4java lib. I just don't see a way how to unsubscribe from all events in the similar way as I subscribe to all at the beginning. I've added question on Digium app dev list: http://lists.digium.com/pipermail/asterisk-app-dev/2017-January/000855.html

**Comment by NaamaGertel** [comment]
Have you tried to use:  "ari.closeAction(ari.events());" instead of "ari.cleanup()" ?

**Comment by modrljin** [comment]
Now I tried it on your suggestion, but it doesn't work and I don't see how this could work because in effect with this code you are creating new ActionEvents object which is not connected yet and invoking 'closeAction' on it doesn't do anything. I think 'cleanup' does the job just fine and closes connected ws properly.
But, it looks like asterisk doesn't deregister ari app at all on closing websocket. Check the following from asterisk CLI log:

**asterisk just started**
maxvoip*CLI> ari show app AriStart
Command 'ari show app AriStart' failed.

**incoming call to app 'AriStart'**
ERROR[10390][C-00000001]: res_stasis.c:1326 stasis_app_exec: Stasis app 'AriStart' not registered

**connecting from java to asterisk, registering app 'AriStart'**
Creating Stasis app 'AriStart'
  == WebSocket connection from '192.168.0.137:51894' for protocol '' accepted using version '13'

**disconnecting java from asterisk, deregistering app 'AriStart'**
Deactivating Stasis app 'AriStart'
  == WebSocket connection from '192.168.0.137:51894' closed

**check ari app status**
maxvoip*CLI> ari show app AriStart
Name: AriStart
  Debug: No
  Subscription Model: Global Resource Subscription
  Subscriptions: 3
    Channels:
      __AST_CHANNEL_ALL_TOPIC (1)
    Bridges:
      __AST_BRIDGE_ALL_TOPIC (1)
    Endpoints:
      __AST_ENDPOINT_ALL_TOPIC (1)

**incoming call to app 'AriStart'**
ERROR[10446][C-00000003]: res_stasis.c:1331 stasis_app_exec: Stasis app 'AriStart' not active
    -- Inactive Stasis app 'AriStart' missed message

----------------------

From the asterisk CLI it is clear that after disconnecting java from asterisk and message "Deactivating Stasis app" - actually nothing is done on Asterisk side. It still considers app as active one.

**Comment by NaamaGertel** [comment]
ok, after investigating this a bit more, it was an ari4java issue and the problem was that the cleanup method did not unsubscribe from all event sources that the stasis application was registered on. After the fix I did not see "missed message" in the CLI. Try to use the ari.cleanup() and If you see this again let me know :)

**Comment by modrljin** [comment]
Good job, congratulations!
