### ISSUE TITLE
Jackson lib performance

### ISSUE THREAD

**Issue by modrljin** [l3nz/ari4java#63]
I've noticed quite big CPU usage from my java app when handling > 100 concurrent calls. Asterisk has 2-3 times lower CPU usage than my java application which is unacceptable. I've made CPU sampling with Java VisualVM tool and it gave me the reason: jackson library doesn't seem to be very fast! Check out my snapshots.

CPU usage results ('top' is command from Debian 8 I have used):
------------------------
1. 10 concurrent calls:
 - java app: Java VisualVM 2-15%
 - java app: 'top' 5-20%
 - asterisk: 'top' 3-5%

2. > 100 calls:
 - java app: Java VisualVM 50-70%
 - java app: 'top' 80-120%
 - asterisk: 'top' 20-30%

Please notice that 'top' shows bigger value than Java VisualVM probably because additional CPU usage from Java VisualVM itself (RMI communication), when I stop it, results are more similar to ones taken from Java VisualVM.

I was googling it and found one interesting site for comparing json libs in java: http://blog.takipi.com/the-ultimate-json-library-json-simple-vs-gson-vs-jackson-vs-json/

Jackson seems to be the best for big json-s, but not for small ones. Since, I believe, json size is quite small here, Jackson doesn't seem to be the best choice here.

![snapshot-100-calls-1](https://cloud.githubusercontent.com/assets/22682901/22587987/262b2e40-ea04-11e6-83e6-8ff56a804b0f.png)
![snapshot-100-calls-2](https://cloud.githubusercontent.com/assets/22682901/22587986/262ab0b4-ea04-11e6-8423-3500196ca624.png)
![snapshot-100-calls-3](https://cloud.githubusercontent.com/assets/22682901/22587988/262e2370-ea04-11e6-8e02-e85045c7d79a.png)
![snapshot-100-calls-4](https://cloud.githubusercontent.com/assets/22682901/22588458/321ce638-ea06-11e6-868e-eda7f783ca3e.png)

Any opinion?

**Comment by l3nz** [comment]
While I'm not especially in love with Jackson, I think the reason why it is so slow is that the Object Mapper used to be re-created on every invocation. This is a known anti-pattern. I'm fixing this.
Please let me know how it goes.

**Comment by l3nz** [comment]
Please test it.
I see you are using the library seriously - why don't you write a "getting started" of sorts?

**Comment by modrljin** [comment]
Great job! Now it works much better. CPU usage from my java app is now about the same as from asterisk. Now, deserializeJson() now takes double less time than onSuccess() handled in my app, while before it took about 10 times more time.

You are correct, I'm trying to use it seriously, you don't? But I'm not really sure what do you mean by asking me to write "getting started of sorts"? You mean if I could write "getting started" manual for ari4java library? Hmm, your README looks quite fine to me. and you know it much better. To be honest, there are few things that I don't understand in your code, e.g. why ARI.setupAction(Object a) "smells bad" according your comment on method and getActionImpl() should be used instead. Currently I'm using setupAction() from other methods, e.g. channels(), ... and everything looks just fine to me.

I'm willing to help you in this project and if you are interested, show you what I'm working on, but probably we should switch to private messaging then, just to make some discussion before. Maybe we can help each other.
