### ISSUE TITLE
Leaked shutDownGroup = new NioEventLoopGroup()

### ISSUE THREAD

**Issue by slaomi** [l3nz/ari4java#64]
Apps using NettyHttpClient won't terminate unless calling exit().

Thread shutDownGroup is still running after NettyHttpClient.destroy()

2 Threads pools are created by NeyytHttpClient's constructor: group and shutDownGroup.
    public NettyHttpClient() {
        group = new NioEventLoopGroup();
        shutDownGroup = new NioEventLoopGroup();
    }

On destroy by destroy(), only group is terminated using shutdownGracefully.
ShutDownGroup is left running.

    public void destroy() {
        // use a different event group to execute the shutdown to avoid deadlocks
        shutDownGroup.schedule(new Runnable() {
            @Override
            public void run() {
                if (wsClientConnection != null) {
                    try {
                        wsClientConnection.disconnect();
                    } catch (RestException e) {
                        // not bubbling exception up, just ignoring
                    }
                }
                if (group != null && !group.isShuttingDown()) {
                    **group.shutdownGracefully(5, 10, TimeUnit.SECONDS).syncUninterruptibly();**
                    group = null;
                }
            }
        }, 250L, TimeUnit.MILLISECONDS);
    }

**Comment by l3nz** [comment]
Want to send in a patch?

**Comment by jsmithe** [comment]
Was having this issues as well.  Took a crack at it.  First time with library or with Netty.  Please let me know if there are any concerns or suggestions.

**Comment by l3nz** [comment]
Looks great. Merging. I'm no expert on Netty either :-)
