### ISSUE TITLE
mailboxes.json not generated

### ISSUE THREAD

**Issue by slaomi** [l3nz/ari4java#65]
Any reason why  mailboxes.json  is not processed by  run.java

    private static void loadAsteriskDefs( DefMapper dm, String srcVer ) throws IOException {

        String srcDir = SOURCES + srcVer + "/";

        dm.clean( srcVer );
        dm.parseJsonDefinition( new File(srcDir + "applications.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "asterisk.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "bridges.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "channels.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "endpoints.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "playbacks.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "recordings.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "sounds.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "deviceStates.json"), srcVer, false );
        dm.parseJsonDefinition( new File(srcDir + "events.json"), srcVer, true );

**//???       dm.parseJsonDefinition( new File(srcDir + "mailboxes.json"), srcVer, false );**
        
    }

**Comment by grahambrown11** [comment]
Need to add it conditionally as it was introduced later...
will apply a fix in due course

**Comment by grahambrown11** [comment]
Fixed with the #127 restructure
