### ISSUE TITLE
ActionChannels 

### ISSUE THREAD

**Issue by shahbour** [l3nz/ari4java#66]
I was using actionChannel on multiple threads but was facing 
```
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@55661481(incomplete)
        at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:251) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:218) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28) ~[netty-all-4.0.25.Final.jar!/:4.0.25.Final]
        at ch.loway.oss.ari4java.tools.http.NettyHttpClient.httpActionSync(NettyHttpClient.java:203) ~[ari4java-0.4.4.jar!/:0.4.4]
```

So what is the best way to use ActionChannel 
1- Create one per thread
2- Create one for each request 
3- Should i close the ActionChannel in case one is created for each request

**Comment by l3nz** [comment]
You should use one per sequence of operations (or per thread) surely you cannot share it.

**Comment by modrljin** [comment]
I'm successfully making calls to asterisk from a lot of threads with single ARI instance. I'm not sure what exactly you are doing in your code, but calling ARI.channels() should work fine from many threads because it creates new ActionChannels object for each call.

INFO for everybody: Definitely try newer version of netty library, I'm using netty-all-4.1.8.Final.jar which is much better! With old one I also had few problems. Not exactly sure now what exceptions were thrown, but I remember there was something with "DefaultChannelPromise.. (incomplete)" randomly fired. Also there was a problem with their internal buffer that was always growing and not emptied properly in some situations which is noticed after a while only when you have a lot of and concurrent calls. With newer version those problems disappeared.

**Comment by shahbour** [comment]
I am using maven and it is using netty-all-4.0.25 , now for the error it mainly popup up when trying to send answer or hangup from inside StasisApplication as the below example

```
public class AsteriskStasis implements AriCallback<Message> {


    private final MessageChannel fromAsterisk;
    private final ARI ari;

    public AsteriskFraudStasis(MessageChannel fromAsterisk,ARI ari) {
        this.fromAsterisk = fromAsterisk;
        this.ari = ari;
    }

    @Override
    public void onSuccess(Message result) {
        log.trace("received Message {}", result);
        if(result instanceof StasisStart) {
            try {
                log.info("Channel Dump has started ");
                StasisStart stasisStart = (StasisStart) result;
                Channel channel = stasisStart.getChannel();
                fromAsterisk.send(MessageBuilder.withPayload(channel.getCaller().getNumber()).build());
                ActionChannels actionChannels = ari.getActionImpl(ActionChannels.class);
                actionChannels.hangup(channel.getId(),"normal");
                ari.closeAction(actionChannels);
            } catch (Exception ex) {
                log.error("Unknown Error",ex);
            }
        }
    }



    @Override
    public void onFailure(RestException e) {
        log.warn("failure on registering App ",e);
    }
}
```
sending hangup from a completely different thread worked perfectly without any single error like below

```
public class AsteriskStasis implements AriCallback<Message> {


    private final MessageChannel fromAsterisk;
    private final ARI ari;
    private ScheduledExecutorService taskScheduler = Executors.newScheduledThreadPool(2);

    public AsteriskFraudStasis(MessageChannel fromAsterisk,ARI ari) {
        this.fromAsterisk = fromAsterisk;
        this.ari = ari;
    }

    @Override
    public void onSuccess(Message result) {
        log.trace("received Message {}", result);
        if(result instanceof StasisStart) {
            try {
                log.info("Channel Dump has started ");
                StasisStart stasisStart = (StasisStart) result;
                Channel channel = stasisStart.getChannel();
                fromAsterisk.send(MessageBuilder.withPayload(channel.getCaller().getNumber()).build());
                taskScheduler.schedule(new Hangup(ari,channel.getId(),"normal"),0, TimeUnit.SECONDS);
            } catch (Exception ex) {
                log.error("Unknown Error",ex);
            }
        }
    }



    @Override
    public void onFailure(RestException e) {
        log.warn("failure on registering App ",e);
    }
}
```

**Comment by l3nz** [comment]
@modrljin you mean I should bump up dependency to netty-all-4.1.8.Final.jar ?

**Comment by shahbour** [comment]
@l3nz for me after using another thread for command sending (other than the one inside Stasis) it worked perfectly and i am handling more that 100 simultaneous call running 24 hour

**Comment by modrljin** [comment]
@l3nz you could do it but probably you should make few tests before to see if it works fine to you as well. As I said, using it I'm not getting some exceptions I used to get before, and memory leakage gone away.

**Comment by MoathAlshorman** [comment]
After facing this issue while developing our ARI application I've concluded the following:
1- Upgrade the version of netty doesn't relate to this issue (I had upgraded to the latest version but the issue stilled there).
2- In these situations, you have to use the asynchronous ARI operations.
E.g. to make an asynchronous ring operation:
`ari.channels().ring("channel-id", new AriCallback<Void>() {

			@Override
			public void onSuccess(Void result) {
			}

			@Override
			public void onFailure(RestException e) {
			}
		    });`

**Comment by MoathAlshorman** [comment]
After facing this issue while developing our ARI application I've concluded the following:
1- Upgrade the version of netty doesn't relate to this issue (I had upgraded to the latest version but the issue stilled there).
2- In these situations, you have to use the asynchronous ARI operations.
E.g. to make an asynchronous ring operation:

> ari.channels().ring(channel-id,new AriCallback<Void>() {

			@Override
			public void onSuccess(Void result) {
			}

			@Override
			public void onFailure(RestException e) {
			}
		    });
