### ISSUE TITLE
Asterisk crash (not ari4java issue)

### ISSUE THREAD

**Issue by modrljin** [l3nz/ari4java#68]
This is more an info to everybody and ask for help to make Asterisk better. And sorry for a long post.

Unfortunately, we all know that Asterisk has a lot of open issues and will always have. But there is one very serious which I have discovered yet in March 2017 [ASTERISK-26868: ARI: Asterisk crash](https://issues.asterisk.org/jira/browse/ASTERISK-26868). Although it is not sure, it seems that issue is related to usage of ARI. What happens is that one of the most important operation 'adding channels to bridge' is crashing asterisk occasionally. I'm experiencing this problem once in a few months on our production server (Asterisk 13.11.2) with mostly 2-5 simultaneous calls, while on a test machines I can reproduce it with about 100 simultaneous calls within one day. Test are made on asterisk 13.11.2 and 14.2.1. Both of them are crashing.

Asterisk bug marshals have accepted the issue, but nothing is going on, nobody fixes it. I was expecting such a big issue to be resolved within a few weeks. Joshua Colp from the Digium told me that unfortunately this issue is still in their queue but there is a lack of users being reported the same problem and who knows when this will be fixed. Obviously there isn't yet a lot of people using ARI seriously. I can't believe that such a basic operation could crash asterisk and probably is not happening when using AGI, AMI or dialplan apps, otherwise who would use it at all?

I have reported on issues tracker different backtraces and debug logs, with and without usage of early bridging (available from asterisk 14 but unfortunately it crashes even more often so I'm still avoiding it). What is even worse, it seems that there is not only one problem. 'segfault' and 'general protection' bugs are happening on different places in asterisk code. Those issues are crashing asterisk completely!

What I'm asking all of you is if you are able to try to reproduce this problem in your test environment, grab the core dump and debug logs and then report on the same issue so they can see that I'm not alone in this. I'm getting this crash on a simple routing application described in a reported issue. I've made test environment with two asterisk machines A and B. A is originating calls to B, B is behaving as router application (receives IN call, sends ring to it, creates bridge and adds IN channel to it. Then app dials on other channel to A as OUT call. When OUT call answers, IN answers as well and OUT is added to the same bridge). When OUT channel is added to bridge, crash happens. Be aware that this issue happens in one of X thousands of calls, sometimes in hundreds of thousands, so it is not easily to get it. But when it happens, all calls are dropped and this is something I can't afford, probably nobody can or should. I was looking for call survival possibilities with HA solutions and asterisk clusters, but didn't go so far till now. Try to run as much as possible simultaneous calls, but probably not more than 120 (120 IN + 120 OUT channels).

Yesterday I got an idea with workaround to put small delay (100 ms) after OUT channel answers and before adding it to bridge to avoid possible 'not-ready' OUT channel, but new crash happened soon. I'm again testing other possibilities and will report them later if anyone is interested in.

Thanks for any help. And sorry for a long post once again!

**Comment by l3nz** [comment]
Any news on this issue?

**Comment by modrljin** [comment]
Well, nobody has fixed it yet on Asterisk side. I have made small intuitive workaround what I have commented on the issue tracker which is working only without early bridging:

> I think I have new valuable input in scenario without early bridging.
> 
> If I put a delay of 100 ms after OUT channel is answered and before it is added to bridge, I can't reproduce asterisk crash any more. To me it looks like newly created and answered OUT channel is sometimes not immediately "ready" yet to be put in bridge and then crash happens. Before I was adding channel to bridge as soon as possible after it is answered (after event ChannelStateChange 'Up') and then crash was occasionally occurring.

**Comment by grahambrown11** [comment]
Closing - not an ari4java issue
