### ISSUE TITLE
JSONMappingException with >= Asterisk 13.13.X

### ISSUE THREAD

**Issue by bweschke** [l3nz/ari4java#72]
asterisk_id field was added to ARI 1.9.0 JSON starting with Asterisk 13.13.0 based on this JIRA issue https://issues.asterisk.org/jira/browse/ASTERISK-26470 - Really, this should have resulted in a bump of ARI from 1.9.0 to 1.9.1 because it was a breaking change for things like ARI4Java, but that didn't happen and now if you try to use ARI4Java with ARI 1.9.0 with Asterisk >= 13.13.0 it fails to work because of the UnsupportedOperationException being thrown. This exception is appropriate for for Asterisk <= 13.13.0 (which is why many are reporting no issues when using 13.7.X up to 13.12.X, but it is not appropriate starting on 13.13.0 moving on up in the 13.X branch.

**Comment by bweschke** [comment]
We have the same problem with video_mode attribute in the bridge object because of https://issues.asterisk.org/jira/browse/ASTERISK-26595

**Comment by bweschke** [comment]
@l3nz - How do you want to handle this? Should we consider adding these fields into the 1.9.0 generated object classes, and then put into the README that for folks using >= 13.13.X of Asterisk they must use the >= 4.5.0 release of ARI4Java?  That seems like the most reasonable approach at this point given that the Asterisk Community is suggesting for people running <= 13.13 of Asterisk 13 LTS to upgrade if they're bringing up issues to be fixed on the 13 LTS branch.

**Comment by jsmithe** [comment]
How do you know which JSON version goes with a particular version of Asterisk?  I kind of trial and error my way into one that worked.

**Comment by sbodmer** [comment]
For asterisk 13+, the `ari.getWebsocketQueue()` call will also fire an unsupported exception because the internal `eventWebsocket(String, Callback)` method is no more supported, only the `eventWebsocket(String, Boolean, Callback)` is supported.
The solution is to add a `ari.getWebsocketQueue(String`) method which will call the supported one...
...Hope this can help someone else, I passed a few day trying to understand why the `ari.getWebsocketQueue()` failed !!!

**Comment by grahambrown11** [comment]
I think this issue will be resolved by the script I've added to always pull the latest from the Asterisk source... I was also thinking of possibly changing the ObjectMapper to be less strict and ignore unknown properties, which has a ramification on 1 test not sure what others...
