### ISSUE TITLE
Channel setCaller/setConnected not working

### ISSUE THREAD

**Issue by wesrosenberg** [l3nz/ari4java#75]
I have implemented dialing of phone calls using channel create and dial, in a manner something like:

            Channel c = ari.channels().create("SIP/bandwidth-primary/"+stripPrefix(callee), 
                    "<app>", 
                    "<more params>",
                    channelID, 
                    "", 
                    strCallerID, 
                    "");
            CallerID_impl_ari_2_0_0 callerID = new CallerID_impl_ari_2_0_0();
            callerID.setNumber(strCallerID);
            callerID.setName(strCallerID);
            c.setCaller(callerID);
            CallerID_impl_ari_2_0_0 connectedID = new CallerID_impl_ari_2_0_0();
            connectedID.setNumber(callee);
            connectedID.setName(callee);
            c.setConnected(connectedID);
            ari.channels().dial(c.getId(), "SIP/kamailio/"+stripPrefix(callee), 60000);

The problem I'm seeing is that neither of the set methods are sticking.  I don't see my callerID come across when the call is made out our SIP trunk, not do I see the data in the event object when handling events related to the call, e.g. StasisStart.

Is this a bug in the library or am I doing something wrong?

Thanks,
Wes

**Comment by jsmithe** [comment]
I think you are confusing your locally scoped state with the state of the channel on the server.  You are setting fields on your local callerID object but then you make a call to the server providing an ID to the channel you want it to use.

I'm not entirely sure what you are trying to accomplish as you did pass in the callerId string when creating the channel.

I've just started using Asterisk and this library recently myself.  However, I believe what you want to do it more asynchronously by handling the events that indicate when the channel is created.  You may also need a bridge for this.  I have always used a bridge but I'd have to check that to be sure.

**Comment by l3nz** [comment]
I would not consider this a bug in the library.
