### ISSUE TITLE
Support for ARI 3.0.0 / Asterisk 15

### ISSUE THREAD

**Issue by l3nz** [l3nz/ari4java#78]
Asterisk 15 beta is out today, and ARI will be version 3.0.0

See https://github.com/asterisk/asterisk/commit/3e8d628c0e3da7a75e4187c6369b873758d53353

**Comment by kelisi** [comment]
hi there, is this project still under maintenance , cause i only see the highest version is  ARI_2_0_0(asterisk 14.2.1) or is there any guide to generate select version of asterisk ari java interface? && Thanks for the project!

**Comment by binarydigit-ro** [comment]
Hello Lenz,

Meanwhile a new version of Asterisk 15.1.3 has appeared and with current release ari4java-0.4.4, connecting using API version ARI_3_0_0 does not work.
Please can you provide a new release updated to version ari4java-0.4.5, to successfully use API version ARI_3_0_0?

Thank you,
Iulius

**Comment by l3nz** [comment]
Apologies - I'll try and run a new build this weekend - I never get a couple of days to finish off the new Clojure code generator. :-(

**Comment by binarydigit-ro** [comment]
Hello Lentz,

If we look at the Asterisk 15.1.4 sources on https://github.com/asterisk/asterisk/tree/master/rest-api we can see the following:

- the file "asterisk/rest-api/resources.json" has been updated with "apiVersion": "3.0.0"
- the rest of the files "asterisk/rest-api/api-docs/*.json" have remained with "apiVersion": "2.0.0"
- the file "asterisk/rest-api/api-docs/bridges.json was updated 2 months ago with "Add mute, dtmf suppression controls" and remained with "apiVersion": "2.0.0"

I think the files *.json in the path "asterisk/rest-api/api-docs/" should be updated to "apiVersion": "3.0.0" before updating the library.

Thank you,
Iulius

**Comment by l3nz** [comment]
The new jar 0.4.5 will be out in a few minutes.
