### ISSUE TITLE
Dial() causes leaking eventfd's

### ISSUE THREAD

**Issue by zicada** [l3nz/ari4java#79]
When using dial(), Asterisk does not close all eventfd's afterwards. This means that with each subsequent call, another eventfd is added to the process-tree. Asterisk will keep running until the ulimit of the underlying OS is hit, and then crash with "too many open files".

When using originate() instead, we do not see the above behavior. This requires a rewrite of all our code that was using dial().

Above behavior is seen using ARI4Java 4.3 and 4.4 on Asterisk 13.x and 14.x, on protocols 1.7 to 1.10.

**Comment by zicada** [comment]
To reproduce, set up a bridge and dial a number using Dial, then add that channel and an incoming channel to the bridge. After the call ends, do lsof -p <pid of asterisk> | grep eventfd  | wc -l

Rince and repeat and watch the number grow until Asterisk crashes with Too many open files.

**Comment by l3nz** [comment]
Did you open up a bug with Asterisk? if it can be reproduced, they will surely be interested in hearing from you.

**Comment by jsmithe** [comment]
If you could reproduce this with a few curl commands that would probably be ideal.  Remove ARIJava from the equation then post up the steps to, https://issues.asterisk.org/jira/browse/ASTERISK

**Comment by l3nz** [comment]
Agreed. While it is definitely important, I don't think it belongs here.

**Comment by zicada** [comment]
I did open up a bug with Asterisk as well on the same day, I just wanted to mention it here as well.
You can track it here:
https://issues.asterisk.org/jira/browse/ASTERISK-27262
They have started looking at it as you can see.
