### ISSUE TITLE
Multiple events received when multiple apps registered

### ISSUE THREAD

**Issue by wesrosenberg** [l3nz/ari4java#81]
Using Asterisk 14.2.1, ari4java 0.4.4, and the following snippets of code:

       String appName = ""app1,app2,app3"";
        ari = ARI.build("http://"+host+":8088/", appName, "login", "password", AriVersion.ARI_2_0_0);

        final MessageQueue mq = new MessageQueue();

        ari.events().eventWebsocket( appName, true, new AriCallback<Message>() {

            @Override
            public void onSuccess(Message result) {                
                q.queue( result );
            }

            @Override
            public void onFailure(RestException e) {
                q.queueError("Err:" + e.getMessage());
            }
        });
        while (run) {
                // process ARI events...
                Message result = mq.dequeueMax( 100, 20 );
        }

I am seeing the same event 3 times.  If I remove app2 and app3 from the build string, I only see one event.

Is this a bug or desired behavior? Seems like a bug to me? Also, I'm pretty sure with v0.4.3 a while back, this behavior did not occur.  is there maybe a newer version to download to fix the problem?

Thanks,
Wes

**Comment by nickname110** [comment]
Because you set subscribeAll parameter to true to your all apps, you will receive same events several times.

Solution: Use app1 only.

**Comment by wesrosenberg** [comment]
Thanks, totally missed the subscribeAll param.

The real solution is to set that to false, and retain the full list of app names, otherwise ARI does not register all apps for Stasis, if you use just app1.
