### ISSUE TITLE
HTTP / Websocket connections should have a timeout

### ISSUE THREAD

**Issue by rattenburg** [l3nz/ari4java#86]
Imagine that the HTTP server does not respond (in time). This can be simulated by opening a TCP port with netcat: ``nc -l -p 8088``

You can see that ari4java is sending its request and then waits eternaly for an answer. This affects all connections: HTTP sync & async, and Websockets.

There should be a (configurable) timeout after which HTTP connections or Websocket pings have to be answered; otherwise the connection should be closed.

**Comment by grahambrown11** [comment]
https://github.com/l3nz/ari4java/commit/3192a20fbaa65a05d8c3b68f2338a50c23647a67 should address this issue, there is still some testing to do to make sure everything works as expected
