### ISSUE TITLE
UnsupportedOperationException, Asterisk 15.2.0 and AriVersion.ARI_3_0_0 

### ISSUE THREAD

**Issue by mohsenk** [l3nz/ari4java#88]
Hi 
I want to execute actionEvents.eventWebSocket function and i give an error.
and i see the ActionEvents_impl_ari_3_0_0 has this implementions : 

```
public Message eventWebsocket(String app) throws RestException {
        throw new UnsupportedOperationException("Method availble from ...");
    }

  public void eventWebsocket(String app, AriCallback<Message> callback) {
        throw new UnsupportedOperationException("Method availble from ...");
    }
```

---

This is my sample code :

```

        ARI ari = new ARI();
        NettyHttpClient hc = new NettyHttpClient();
        hc.initialize("http://.../", "...", "...");
        ari.setHttpClient(hc);
        ari.setWsClient(hc);
        ari.setVersion(AriVersion.ARI_3_0_0);
        ActionEvents actionEvents = ari.getActionImpl(ActionEvents.class);
        actionEvents.eventWebsocket("hello", new AriCallback<Message>() {
            @Override
            public void onSuccess(Message message) {
                System.out.println(message);
            }

            @Override
            public void onFailure(RestException e) {
                e.printStackTrace();
            }
        });
```

**Comment by narrow89** [comment]
You need to add a parameter to eventWebsocket Method.

` ARI ari = new ARI();
        
        ari = ARI.build("HOST", "APP", "USER", "PASS",
                AriVersion.ARI_3_0_0);
        
        ActionEvents actionEvents = ari.getActionImpl(ActionEvents.class);
        actionEvents.eventWebsocket("hello",true, new AriCallback<Message>() {


            @Override
            public void onSuccess(Message result) {
                System.out.println(message);
            }

            @Override
            public void onFailure(RestException e) {

            }
        });`

**Comment by NaamaGertel** [comment]
Right, you need to connect the websocket to ARI instance. First, I create an ARI instance:
ARI ari = ARI.build(url, appName, login, pass, AriVersion.ARI_2_0_0);

Second, I open a websocket with:
ari.events().eventWebsocket(appName, true, new AriCallback<Message>(){
 @Override
        public void onSuccess(Message result) {
                  //implementation here
        }

        @Override
        public void onFailure(RestException e) {
            //implementation here
        }
});

I'm closing this issue, if you need any help let me know and I'll reopen it :)
