### ISSUE TITLE
[REL0.4.5] Events websocket fails to connect with Netty 4.0.45/4.1.8 and later

### ISSUE THREAD

**Issue by guss77** [l3nz/ari4java#91]
In release 0.4.5, a recent change in Netty causes the websocket connection to `/events` to crash during the websocket handshake, and be retried endlessly.

A workaround for this issue is introduced to ari4java in commit [6bd217f5bcaea4f7f1ede86ba2a24323755b4faf](https://github.com/l3nz/ari4java/commit/6bd217f5bcaea4f7f1ede86ba2a24323755b4faf).

When running under Vert.x 3.5, we need to update Netty to 4.1.19 otherwise we get conflicts between the ari4java Netty dependency and the Vert.x dependency.

Is it possible to release an updated ari4java release that includes this workaround?

**Comment by guss77** [comment]
Yes, and issue a release through Bintray. Thanks!

**Comment by VladimirBelyakof** [comment]
I join the request to make it possible to work with new versions netty
