### ISSUE TITLE
Unable to use channels.originateWithId method in ActionChannels_impl_ari_2_0_0

### ISSUE THREAD

**Issue by NaamaGertel** [l3nz/ari4java#94]
Hello,

I'm trying to create a new channel using the method ari.channels.originateWithId in class  ActionChannels_impl_ari_2_0_0 and calling it in the following way: 				"ari.channels().originateWithId(endPointChannelId, endPoint, null, null ,1 , null, getAppName(), null, getChannelId(),-1 ,headers, null, getChannelId(),""); " , when getChannelId() returns the channel id of the calling channel (the originator) , endpoint ="SIP/app2", and headers is a Map<String,String>.

I'm creating this channel in order to add it to a bridge and then use channels().dial method in order to dial from the caller to the new channel. My application uses docker, so I used docker CLI and "ari set debug all on" in order to debug and this is a part from what I see (the relevant part when the channel was created):
{
  "type": "ChannelCreated",
  "timestamp": "2018-05-06T15:29:08.467+0000",
  "channel": {
    "id": "6293d74e-ba9f-4a21-a480-47f2a003f7c8",
    "name": "SIP/app2-00000047",
    "state": "Down",
    "caller": {
      "name": "",
      "number": ""
    },
    "connected": {
      "name": "",
      "number": ""
    },
    "accountcode": "",
    "dialplan": {
      "context": "ari-context",
      "exten": "s",
      "priority": 1
    },
    "creationtime": "2018-05-06T15:29:08.466+0000",
    "language": "en"
  },
  "asterisk_id": "02:42:ac:17:00:06",
  "application": "stasisApp"
}
<--- Sending ARI event to 172.23.0.1:35954 --->
{
  "variable": "SIPCALLID",
  "value": "1e1212836ebc81db163c40ef4f260a01@172.23.0.6:5060",
  "type": "ChannelVarset",
  "timestamp": "2018-05-06T15:29:08.467+0000",
  "channel": {
    "id": "6293d74e-ba9f-4a21-a480-47f2a003f7c8",
    "name": "SIP/app2-00000047",
    "state": "Down",
    "caller": {
      "name": "",
      "number": ""
    },
    "connected": {
      "name": "",
      "number": ""
    },
    "accountcode": "",
    "dialplan": {
      "context": "ari-context",
      "exten": "s",
      "priority": 1
    },
    "creationtime": "2018-05-06T15:29:08.466+0000",
    "language": "en"
  },
  "asterisk_id": "02:42:ac:17:00:06",
  "application": "stasisApp"
}

When I do the dial from the caller to the new channel I get:
<--- Sending ARI response to 172.23.0.1:35640 --->
422 Unprocessable Entity
Content-type: application/json
{
  "message": "Channel not in Stasis application"
}

I'm not sure what I'm doing wrong and I would love for some help. If more information is needed I will add.
Thanks!

**Comment by grahambrown11** [comment]
@NaamaGertel did you come right? There is an example in the tests folder - [ConnectAndDial](https://github.com/l3nz/ari4java/blob/master/src/test/java/ch/loway/oss/ari4java/sandbox/sample/ConnectAndDial.java)
