### ISSUE TITLE
Support to Application_AddQueueMember

### ISSUE THREAD

**Issue by NaamaGertel** [l3nz/ari4java#98]
Hi,
I’m using ari4java version 2_0_0 and I’m trying to find a method that supports queue adding/removing etc. of agents. I saw on Asterisk 14 wiki that there exists “Application_AddQueueMember”  (https://wiki.asterisk.org/wiki/display/AST/Asterisk+14+Application_AddQueueMember) and I’m trying to find an equivalent way/method to implement it with ARI. 
Is ari4java supports that? If it’s not possible to implement a queue using ARI I would also love to hear about it.

Thanks

**Comment by l3nz** [comment]
I think that there is no simple way to use Applications from ARI - it's actually working at a different level, because it is meant as an application itself.
